### ISSUE TITLE
Doesnt work on MIUI

### ISSUE THREAD

**Issue by warlockers** [gjf/gjf_bt#9]
I found that this modification does not work on MIUIv8 (Android 6) nor on MIUIv9 (Android 7.1) Redmi 4X. After analyzing the problem, I found out that the problem occurs in the libbluetooth_jni.so file stored in /system/lib/ . After applying the mod, bluetooth stops working completely and this file is to blame. There are probably some other pointers in it, since the *.so file is practically a DLL library in machine code, I'm not technically proficient to modify it to work. Can you help me somehow if I upload the stock MIUI file for comparison?

**Comment by gjf** [comment]
This project was made a long time ago when Android didn't allow to change bitrate and codecs for BT.
I think it is clearly stated in Readme (but who reads it really?)
Now I don't have such an obsolete devices for test - and also I don't have any interest in playing with obsolete code.
So I really recommend to move to newer Android 10 or even higher that solves this problem by design.

**Comment by warlockers** [comment]
Both we know  that is not all about Android version. Codecs must be presented at ROM by Manufacturer. So yes new Androids are capable to change codecs trough DEV MENU, but APTX doesnt need to be there. I am a fan of the old versions of miui, which were still interesting in their design. Plus, the older devices still fit in my pocket. So I have no reason to upgrade. But of course I understand your reason ...
